services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: "Conformance!Pass2026"
    ports:
      - "${ODBC_SQLSERVER_PORT:-1433}:1433"
