//! `sqldev init` — bootstrap a project layout from a live database.
//!
//! Behaviour:
//! - Refuses to overwrite an existing `.sqldev.yml` unless `--force`.
//! - Creates `migrations/`, `seeds/`, `models/` directories.
//! - Introspects the active connection and writes
//!   `migrations/0001_baseline.sql` containing all CREATE statements
//!   (DDL-only, deterministic order).
//! - Writes a starter `.sqldev.yml` whose `dev` env points at the active
//!   connection, with the password sourced from `${SQLDEV_PASSWORD}`.
//! - Adds `.sqldev.local.yml` (and friends) to `.gitignore`, creating the
//!   file if needed.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use clap::Args as ClapArgs;
use sqldev_conn::AuthOptions;

use crate::config_ctx::ConfigContext;
use crate::conn_flags::ConnectionFlags;

#[derive(ClapArgs, Debug)]
pub struct Args {
    #[command(flatten)]
    pub conn: ConnectionFlags,

    /// Project root. Defaults to the current directory.
    #[arg(long)]
    pub path: Option<PathBuf>,

    /// Overwrite an existing `.sqldev.yml` if present.
    #[arg(long)]
    pub force: bool,

    /// Skip database introspection. Writes an empty baseline migration.
    /// Useful when scaffolding before the database exists yet.
    #[arg(long)]
    pub no_baseline: bool,
}

pub async fn run(args: Args, ctx: &ConfigContext) -> Result<()> {
    let root = args.path.clone().unwrap_or_else(|| PathBuf::from("."));
    fs::create_dir_all(&root).with_context(|| format!("create {}", root.display()))?;

    let cfg_path = root.join(".sqldev.yml");
    if cfg_path.exists() && !args.force {
        bail!(
            "{} already exists; pass --force to overwrite",
            cfg_path.display()
        );
    }

    // Resolve connection options now so any error happens before we touch
    // the filesystem.
    let opts = args
        .conn
        .resolve(ctx.env_block())
        .context("resolve connection options")?;

    // ---- Layout ---------------------------------------------------------
    for sub in ["migrations", "seeds", "models"] {
        let p = root.join(sub);
        fs::create_dir_all(&p).with_context(|| format!("create {}", p.display()))?;
        // Marker file so `git add .` picks the empty dirs up.
        let keep = p.join(".gitkeep");
        if !keep.exists() {
            fs::write(&keep, b"").with_context(|| format!("write {}", keep.display()))?;
        }
    }

    // ---- Baseline migration --------------------------------------------
    let baseline_path = root.join("migrations").join("0001_baseline.sql");
    let baseline_sql = if args.no_baseline {
        "-- 0001_baseline.sql\n-- Generated by `sqldev init --no-baseline`.\n-- Add your initial schema here.\n"
            .to_string()
    } else {
        let mut client = sqldev_conn::connect(&opts)
            .await
            .context("connect to SQL Server for baseline introspection")?;
        let graph = sqldev_introspect::build_schema_graph(&mut client, &opts.database)
            .await
            .context("introspect baseline schema")?;
        let header = format!(
            "-- 0001_baseline.sql\n-- Generated by `sqldev init` from database `{}`.\n-- Re-running init with --force overwrites this file.\n\n",
            opts.database
        );
        header + &sqldev_ddl::baseline_ddl(&graph)
    };
    fs::write(&baseline_path, baseline_sql)
        .with_context(|| format!("write {}", baseline_path.display()))?;

    // ---- .sqldev.yml ----------------------------------------------------
    let user = match &opts.auth {
        AuthOptions::Sql { user, .. } => user.clone(),
    };
    let trust = if opts.trust_server_certificate {
        "true"
    } else {
        "false"
    };
    let yml = format!(
        "# .sqldev.yml - generated by `sqldev init`.\n\
         # The password is interpolated from the SQLDEV_PASSWORD env var so the\n\
         # file is safe to commit. Override per-shell, or put environment-specific\n\
         # secrets in `.sqldev.local.yml` (gitignored).\n\
         default_env: dev\n\
         envs:\n  \
         dev:\n    \
         host: {host}\n    \
         port: {port}\n    \
         database: {database}\n    \
         auth:\n      \
         kind: sql\n      \
         user: {user}\n      \
         password: ${{SQLDEV_PASSWORD}}\n    \
         trust_server_certificate: {trust}\n",
        host = opts.host,
        port = opts.port,
        database = opts.database,
    );
    fs::write(&cfg_path, yml).with_context(|| format!("write {}", cfg_path.display()))?;

    // ---- .gitignore -----------------------------------------------------
    let gi_path = root.join(".gitignore");
    ensure_gitignore_lines(
        &gi_path,
        &[
            "# Added by sqldev init",
            ".sqldev.local.yml",
            ".sqldev.local.yaml",
        ],
    )
    .with_context(|| format!("update {}", gi_path.display()))?;

    eprintln!("✔ Wrote {}", cfg_path.display());
    eprintln!("✔ Wrote {}", baseline_path.display());
    eprintln!("✔ Project layout ready at {}", root.display());
    Ok(())
}

/// Append `lines` to `path` (creating it if necessary) when none of them
/// already appears. Each line is matched against the file's existing lines
/// after trimming trailing whitespace.
fn ensure_gitignore_lines(path: &Path, lines: &[&str]) -> Result<()> {
    let existing = if path.exists() {
        fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?
    } else {
        String::new()
    };
    let known: std::collections::BTreeSet<&str> = existing.lines().map(str::trim_end).collect();
    let mut added: Vec<&str> = Vec::new();
    for &l in lines {
        if !known.contains(l) {
            added.push(l);
        }
    }
    if added.is_empty() {
        return Ok(());
    }
    let mut new_content = existing.clone();
    if !new_content.is_empty() && !new_content.ends_with('\n') {
        new_content.push('\n');
    }
    if !new_content.is_empty() {
        new_content.push('\n');
    }
    for l in added {
        new_content.push_str(l);
        new_content.push('\n');
    }
    fs::write(path, new_content).with_context(|| format!("write {}", path.display()))?;
    Ok(())
}
