//! `sqldev diff` subcommand.
//!
//! Compares two schema graphs and emits a T-SQL migration script.
//! Each side may come from one of:
//!   * a path to a JSON schema-graph file (produced by `sqldev introspect`)
//!   * a live database (introspected on demand) via `--old-db` / `--new-db`

use anyhow::{Context, Result, bail};
use clap::Args as ClapArgs;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use crate::config_ctx::ConfigContext;
use crate::conn_flags::ConnectionFlags;
use sqldev_core::SchemaGraph;
use sqldev_diff::DiffResult;

#[derive(ClapArgs, Debug)]
#[allow(clippy::struct_excessive_bools)]
pub struct Args {
    /// Old (current) schema-graph JSON file.
    #[arg(long, conflicts_with = "old_db", group = "old_src")]
    pub old: Option<PathBuf>,
    /// New (target) schema-graph JSON file.
    #[arg(long, conflicts_with = "new_db", group = "new_src")]
    pub new: Option<PathBuf>,
    /// Treat the configured connection as the "old" side; live-introspect it.
    #[arg(long, conflicts_with = "old", group = "old_src")]
    pub old_db: bool,
    /// Treat the configured connection as the "new" side; live-introspect it.
    #[arg(long, conflicts_with = "new", group = "new_src")]
    pub new_db: bool,

    #[command(flatten)]
    pub conn: ConnectionFlags,

    /// Suppress the trailing `-- warnings` block on stderr.
    #[arg(long)]
    pub quiet: bool,

    /// Write the diff as a numbered migration file into this directory
    /// (e.g. `--output migrations`). The next available `NNNN_<name>.sql`
    /// name is chosen, with `-- +sqldev Up` set to the forward diff and
    /// `-- +sqldev Down` set to the reverse diff. Without this flag the
    /// statements are printed to stdout.
    #[arg(long)]
    pub output: Option<PathBuf>,

    /// Name used for the generated migration file (sanitized).
    /// Defaults to `diff`.
    #[arg(long, requires = "output")]
    pub name: Option<String>,

    /// Allow writing the migration file even when the differ produced
    /// warnings (otherwise the write is refused so partial migrations
    /// don't get committed).
    #[arg(long, requires = "output")]
    pub allow_warnings: bool,
}

pub async fn run(args: Args, ctx: &ConfigContext) -> Result<()> {
    let old = load_side(args.old.as_deref(), args.old_db, &args.conn, ctx, "old").await?;
    let new = load_side(args.new.as_deref(), args.new_db, &args.conn, ctx, "new").await?;

    let result = sqldev_diff::diff(&old, &new);

    if let Some(dir) = args.output.as_deref() {
        let reverse = sqldev_diff::diff(&new, &old);
        let name = args.name.as_deref().unwrap_or("diff");
        write_migration(
            dir,
            name,
            &result,
            &reverse,
            args.allow_warnings,
            args.quiet,
        )?;
        return Ok(());
    }

    if result.statements.is_empty() {
        println!("-- no changes");
    } else {
        for stmt in &result.statements {
            println!("{stmt}");
        }
    }
    if !args.quiet {
        for w in &result.warnings {
            eprintln!("[diff] {w}");
        }
    }
    Ok(())
}

fn write_migration(
    dir: &Path,
    name: &str,
    forward: &DiffResult,
    reverse: &DiffResult,
    allow_warnings: bool,
    quiet: bool,
) -> Result<()> {
    if forward.statements.is_empty() && reverse.statements.is_empty() {
        println!("-- no changes; nothing to write");
        return Ok(());
    }
    if !allow_warnings && (!forward.warnings.is_empty() || !reverse.warnings.is_empty()) {
        for w in forward.warnings.iter().chain(reverse.warnings.iter()) {
            eprintln!("[diff] {w}");
        }
        bail!(
            "refusing to write migration: differ produced {} warning(s) (re-run with --allow-warnings to override)",
            forward.warnings.len() + reverse.warnings.len()
        );
    }

    fs::create_dir_all(dir).with_context(|| format!("create {}", dir.display()))?;
    let next = next_version(dir)?;
    let file_name = format!("{:04}_{}.sql", next, sanitize_name(name));
    let path = dir.join(&file_name);
    if path.exists() {
        bail!("{} already exists", path.display());
    }

    let mut body = String::new();
    writeln!(body, "-- {file_name}").unwrap();
    body.push_str("-- Generated by `sqldev diff --output`.\n\n");
    body.push_str("-- +sqldev Up\n");
    if forward.statements.is_empty() {
        body.push_str("-- (no forward changes)\n");
    } else {
        for stmt in &forward.statements {
            body.push_str(stmt);
            body.push('\n');
        }
    }
    body.push_str("\n-- +sqldev Down\n");
    if reverse.statements.is_empty() {
        body.push_str("-- (no reverse changes)\n");
    } else {
        for stmt in &reverse.statements {
            body.push_str(stmt);
            body.push('\n');
        }
    }

    fs::write(&path, body).with_context(|| format!("write {}", path.display()))?;
    println!("Wrote {}", path.display());

    if !quiet {
        for w in forward.warnings.iter().chain(reverse.warnings.iter()) {
            eprintln!("[diff] {w}");
        }
    }
    Ok(())
}

fn sanitize_name(raw: &str) -> String {
    let mut out = String::with_capacity(raw.len());
    for ch in raw.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
        } else if matches!(ch, ' ' | '-' | '_') {
            out.push('_');
        }
    }
    if out.is_empty() {
        out.push_str("diff");
    }
    out
}

fn next_version(dir: &Path) -> Result<u32> {
    let mut max_seen: u32 = 0;
    if !dir.exists() {
        return Ok(1);
    }
    for entry in fs::read_dir(dir).with_context(|| format!("read {}", dir.display()))? {
        let entry = entry?;
        let name = entry.file_name();
        let name = name.to_string_lossy();
        // Match `NNNN_anything.sql` (NNNN must be ASCII digits).
        let Some((stem, ext)) = name.rsplit_once('.') else {
            continue;
        };
        if ext != "sql" {
            continue;
        }
        let Some((ver, _)) = stem.split_once('_') else {
            continue;
        };
        if let Ok(n) = ver.parse::<u32>() {
            max_seen = max_seen.max(n);
        }
    }
    Ok(max_seen + 1)
}

async fn load_side(
    file: Option<&std::path::Path>,
    live: bool,
    conn: &ConnectionFlags,
    ctx: &ConfigContext,
    side: &str,
) -> Result<SchemaGraph> {
    if let Some(path) = file {
        let text = fs::read_to_string(path)
            .with_context(|| format!("reading --{side} {}", path.display()))?;
        return serde_json::from_str(&text)
            .with_context(|| format!("parsing schema graph for --{side}"));
    }
    if live {
        let opts = conn
            .resolve(ctx.env_block())
            .context("resolve connection options")?;
        let mut client = sqldev_conn::connect(&opts)
            .await
            .context("connect to SQL Server")?;
        return sqldev_introspect::build_schema_graph(&mut client, &opts.database)
            .await
            .context("build schema graph");
    }
    bail!("must specify either --{side} <file> or --{side}-db");
}
